homeassistant:
  name: Home
  latitude: !secret lat
  longitude: !secret lon
  elevation: 73
  unit_system: metric
  time_zone: Australia/Melbourne
  customize: !include misc/customize.yaml
  packages: !include_dir_named packages/

frontend:

config:

# NOTE: Using nginx to front this
# https://home-assistant.io/docs/ecosystem/nginx/
http:
  api_password: !secret http_password

updater:

discovery:

conversation:

history:

recorder:
  purge_days: 7

logbook: !include_dir_merge_named logbook/

logger:
  default: warn

sun:

tts:
  - platform: google

ifttt:
  key: !secret ifttt_api

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: home-assistant-1
  username: !secret mqtt_username
  password: !secret mqtt_pwd

emulated_hue:
  expose_by_default: true
  exposed_domains:
    - light

device_tracker:
  - platform: owntracks
  - platform: netgear
    host: 192.168.1.1
    username: admin
    password: !secret netgear_pwd
    track_new_devices: false

ring:
  username: !secret ring_user
  password: !secret ring_pwd

zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/homeassistant/src/python-openzwave/openzwave/config 
  device_config: !include zwave_device_config.yaml

sensor: !include_dir_list sensors/
zone: !include_dir_list zones/
group: !include groups.yaml

script: !include_dir_merge_named scripts/
automation: !include_dir_merge_list automation/
