- alias: "entry movement away"
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: sensor.aeotec_multisensor_motion_template_1
      state: "motion detected"
  condition:
    - condition: state
      entity_id: input_boolean.disable_auto_motion
      state: "off"
    - condition: state
      entity_id: device_tracker.jon_mobile
      state: "not_home"
  action:
    service: notify.pb
    data:
      title: "Motion detected"
      message: "There is motion in your entry hall!"
