- alias: "entry movement day"
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: sensor.aeotec_multisensor_motion_template_1
      state: "motion detected"
  condition:
    - condition: state
      entity_id: sun.sun
      state: "above_horizon"
    - condition: state
      entity_id: input_boolean.disable_auto_motion
      state: "off"
  action:
    service: script.motion_entry_bright
