- alias: "garage auto close"
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: sensor.aeotec_multisensor_motion_template_1
      state: "motion detected"
  condition:
    - condition: state
      entity_id: binary_sensor.garage_door
      state: "on"
    - condition: state
      entity_id: input_boolean.disable_auto_motion
      state: "off"
  action:
    service: switch.turn_off
    entity_id: switch.garage_door
