- alias: "garage door away"
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_door
      state: "on"
  condition:
    - condition: state
      entity_id: input_boolean.disable_auto_motion
      state: "off"
    - condition: state
      entity_id: device_tracker.jon_mobile
      state: "not_home"
  action:
    service: notify.pb
    data:
      title: "Garage Door OPEN!"
      message: "Your garage door is open!"
