- alias: "jon sleeping"
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: binary_sensor.jon_sleeping
      state: "on"
  condition:
    - condition: state
      entity_id: input_boolean.disable_auto_presence
      state: "off"
  action:
    - service: scene.turn_on
      entity_id: scene.all_off

