- alias: "jon leave"
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: device_tracker.jon_mobile
      from: "home"
      to: "not_home"
  condition:
    - condition: state
      entity_id: input_boolean.disable_auto_presence
      state: "off"
  action:
    - service: scene.turn_on
      entity_id: scene.all_off

