homeassistant:
  customize:
    sensor.aeotec_zw100_multisensor_6_burglar_3_10:
      friendly_name: Entry Motion
    sensor.aeotec_zw100_multisensor_6_luminance_3_3:
      friendly_name: Entry Lux
    sensor.aeotec_zw100_multisensor_6_relative_humidity_3_5:
      friendly_name: Entry Humidity
    sensor.aeotec_zw100_multisensor_6_temperature_3_1:
      friendly_name: Entry Temperature
    sensor.aeotec_zw100_multisensor_6_ultraviolet_3_27:
      friendly_name: Entry UV
