# Thanks to JesseWebDotCom - https://github.com/JesseWebDotCom/home-assistant-configuration/blob/master/packages/ha.yaml
homeassistant:
  customize:
    script.backup:
      icon: mdi:zip-box
      friendly_name: Backup Home Assistant

automation:
  - alias: BACKUP (DAILY) Home Assistant
    hide_entity: True
    trigger:
      platform: time
      hours: 1
      minutes: 1
      seconds: 0
    action:
      - service: shell_command.backup

shell_command:
  # BACKUP - 1 FILE PER MONTH, OVERWRITE
  backup: 7z u -r "/mnt/NASJB/backup/HomeAssistant/backup-$(date +"%m%Y").zip" /home/homeassistant/.homeassistant

script:
  backup:
    alias: Backup Home Assistant
    sequence:
      - service: shell_command.backup_zip
