switch:
  - platform: mqtt
    name: "Garage Door"
    state_topic: "garage/door/binary"
    command_topic: "garage/door/switch"
    retain: false

binary_sensor:
  - platform: mqtt
    name: "Garage Door"
    state_topic: "garage/door/binary"
    device_class: opening

homeassistant:
  customize:
    switch.garage_door:
      icon: mdi:garage-open
